name: Verify configuration

on:
  pull_request:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: opentofu/setup-opentofu@v1
      - uses: actions/checkout@v4
      - run: tofu fmt -recursive -check -diff
